'use client';
import {useEffect,useRef,useState} from 'react';
type Mode='auto'|'direct'|'port'; type Device='universal'|'iphone'|'ipad'; type Tab='convert'|'jobs'|'guide';
type Job={id:string;name:string;status:'working'|'completed'|'failed';progress:number;stage:string;createdAt:string;mode?:string;error?:string;blob?:Blob;artifactName?:string};
const MAX=350*1024*1024;
const labels={auto:'Smart Auto',direct:'Direct IPA',port:'Port Project'} as const;
function id(){return Date.now().toString(36)+'-'+crypto.getRandomValues(new Uint32Array(1))[0].toString(36)}
export function DebToIPAPortApp(){
 const [boot,setBoot]=useState(true),[tab,setTab]=useState<Tab>('convert'),[file,setFile]=useState<File|null>(null),[mode,setMode]=useState<Mode>('auto'),[device,setDevice]=useState<Device>('universal'),[ios,setIos]=useState('15.0'),[name,setName]=useState(''),[bundle,setBundle]=useState(''),[jobs,setJobs]=useState<Job[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''); const worker=useRef<Worker|null>(null);
 useEffect(()=>{const t=setTimeout(()=>setBoot(false),700);return()=>clearTimeout(t)},[]); useEffect(()=>()=>worker.current?.terminate(),[]);
 function choose(f?:File){if(!f)return;if(!f.name.toLowerCase().endsWith('.deb')){setFile(null);setNotice('Choose a file ending in .deb.');return}if(f.size>MAX){setFile(null);setNotice('This package is over the 350 MB mobile limit.');return}setNotice('');setFile(f)}
 function save(j:Job){if(!j.blob||!j.artifactName)return;const u=URL.createObjectURL(j.blob),a=document.createElement('a');a.href=u;a.download=j.artifactName;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)}
 async function run(){if(!file||busy)return;const source=file,jid=id();setBusy(true);setTab('jobs');setJobs(v=>[{id:jid,name:source.name,status:'working',progress:5,stage:'Reading package',createdAt:new Date().toISOString()},...v]);try{const buffer=await source.arrayBuffer(),w=new Worker('/converter-worker.js',{type:'module'});worker.current=w;w.onmessage=e=>{const m=e.data||{};if(m.type==='engine'||m.type==='progress'){setJobs(v=>v.map(j=>j.id===jid?{...j,progress:Math.max(j.progress,Number(m.progress)||10),stage:String(m.message||'Inspecting package')}:j));return}if(m.type==='complete'){const verdict=String(m.result?.verdict||'blocked'),port=verdict==='port-project',host=verdict==='host-packaged',direct=verdict==='packaged',ok=direct||port||host,featureComplete=Boolean(m.result?.hostBuild?.featureComplete),warnings=Array.isArray(m.result?.warnings)?m.result.warnings.join(' '):'',blob=new Blob([m.buffer],{type:'application/zip'}),blockers=Array.isArray(m.result?.blockers)?m.result.blockers.join(' '):'';setJobs(v=>v.map(j=>j.id===jid?{...j,status:ok?'completed':'failed',progress:100,mode:host?(featureComplete?'Compatible IPA':'Host IPA · partial'):port?'Port Project':'Direct IPA',stage:host?(featureComplete?'Automatically rebuilt compatible IPA ready':'Launchable compatibility IPA and Port Project ready'):port?'Port Project and replacement plan ready':direct?'Unsigned IPA ready':'Compatibility report ready',error:host&&!featureComplete?(warnings||'The IPA launches safely, but unsupported original features still require a public-API replacement.'):ok?undefined:(blockers||'Conversion was blocked.'),blob,artifactName:m.result?.artifactName||source.name+'-DebToIPA-result.zip'}:j));setBusy(false);setFile(null);w.terminate();worker.current=null}if(m.type==='error'){setJobs(v=>v.map(j=>j.id===jid?{...j,status:'failed',progress:100,stage:'Engine error',error:String(m.message||'Conversion failed')}:j));setBusy(false);w.terminate();worker.current=null}};w.onerror=e=>{setJobs(v=>v.map(j=>j.id===jid?{...j,status:'failed',progress:100,stage:'Engine failed to load',error:e.message||'Load failed'}:j));setBusy(false);worker.current=null};w.postMessage({id:jid,buffer,options:{sourceName:source.name,mode,device,minimumIos:ios,displayName:name,bundleId:bundle}},[buffer])}catch(e){setJobs(v=>v.map(j=>j.id===jid?{...j,status:'failed',progress:100,stage:'Conversion failed',error:e instanceof Error?e.message:String(e)}:j));setBusy(false)}}
 if(boot)return <main className="boot-screen"><div className="ambient ambient-a"/><div className="boot-mark">✦<span className="boot-orbit"/></div><h1>DebToIPA</h1><p>Loading Direct, Host, and Port engines</p><div className="boot-loader"><span/></div></main>;
 return <main className="app-shell"><div className="noise"/><div className="ambient ambient-a"/><div className="ambient ambient-b"/><header className="topbar"><div className="brand"><div className="brand-mark">✦</div><div><strong>DebToIPA</strong><span>Direct conversion + automatic stock-iOS host</span></div></div><div className="runner-pill"><span/>On device</div></header><div className="content">
 {tab==='convert'&&<section className="view enter"><div className="hero-copy"><p className="eyebrow">DIRECT + AUTO REBUILD</p><h1>Convert the app. <span>Replace the jailbreak parts.</span></h1><p>Smart Auto first tries the original app. If stock iOS cannot run it, DebToIPA injects translated files and capabilities into a precompiled Swift compatibility host and returns a launchable unsigned IPA plus the full Port Project.</p></div>
 <label className={'upload-zone '+(file?'has-file':'')} style={{position:'relative'}}><input type="file" aria-label="Choose a Debian package" onChange={e=>choose(e.target.files?.[0])} style={{position:'absolute',inset:0,width:'100%',height:'100%',opacity:0,zIndex:2}}/><div className="upload-icon">{file?'✓':'⇧'}</div><strong>{file?.name||'Choose your Debian package'}</strong><span>{file?`${(file.size/1048576).toFixed(1)} MB · ready`:'iPhone Files · up to 350 MB'}</span></label>
 <div className="settings-card"><div className="section-title"><div><p className="eyebrow">STRATEGY</p><h2>Conversion mode</h2></div><span>⚡</span></div><div className="segmented">{(['auto','direct','port'] as Mode[]).map(v=><button key={v} className={mode===v?'active':''} onClick={()=>setMode(v)}>{labels[v]}</button>)}</div><p style={{color:'var(--muted)',fontSize:12,lineHeight:1.55}}>{mode==='auto'?'Build a direct IPA when possible; otherwise automatically build a launchable compatibility-host IPA and include its Port Project.':mode==='direct'?'Only package the original ARM64 app when the complete Debian payload is stock-iOS compatible.':'Generate the editable Swift replacement project without building the compatibility-host IPA.'}</p><div className="section-title"><div><p className="eyebrow">TARGET</p><h2>Device compatibility</h2></div><span>◇</span></div><div className="segmented">{(['universal','iphone','ipad'] as Device[]).map(v=><button key={v} className={device===v?'active':''} onClick={()=>setDevice(v)}>{v==='universal'?'Universal':v==='iphone'?'iPhone':'iPad'}</button>)}</div><div className="field-grid"><label><span>Minimum iOS</span><input value={ios} onChange={e=>setIos(e.target.value)} inputMode="decimal"/></label><label><span>Display name <em>optional</em></span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Keep original"/></label><label className="full"><span>Bundle ID <em>optional</em></span><input value={bundle} onChange={e=>setBundle(e.target.value)} placeholder="com.example.portedapp" autoCapitalize="none"/></label></div></div>{notice&&<div className="notice">ⓘ <span>{notice}</span></div>}<button className="primary convert-button" disabled={!file||busy} onClick={run}>⚡ {busy?'Building result…':mode==='port'?'Generate Port Project':'Build compatible IPA'}</button><div className="truth-card">ⓘ <p><strong>No crash-on-launch repacks:</strong> Smart Auto never executes the blocked jailbreak binary inside the host IPA. It strips nested native code, embeds safe assets and configuration, and shows any unimplemented private capability inside the app instead of silently crashing.</p></div></section>}
 {tab==='jobs'&&<section className="view enter"><div className="view-heading"><div><p className="eyebrow">ACTIVITY</p><h1>Local jobs</h1></div><span>{jobs.length}</span></div>{!jobs.length&&<div className="empty-state"><div className="upload-icon">▤</div><h2>No conversions yet</h2><p>Direct IPAs, compatibility-host IPAs, and Port Projects appear here.</p><button className="secondary" onClick={()=>setTab('convert')}>Start a conversion</button></div>}<div className="job-list">{jobs.map(j=><article className="job-card" key={j.id}><div className="job-top"><div className={'job-status '+(j.status==='working'?'in_progress':j.status)}>{j.status==='completed'?'✓':j.status==='failed'?'!':'▤'}</div><div className="job-name"><strong>{j.name}</strong><span>{new Date(j.createdAt).toLocaleString()}</span></div><span className={'status-label '+(j.status==='working'?'in_progress':j.status)}>{j.mode||j.status}</span></div><div className="progress-track"><span style={{width:j.progress+'%'}}/></div><div className="job-meta"><span>{j.stage}</span><strong>{j.progress}%</strong></div>{j.error&&<p className="job-error">{j.error}</p>}<div className="job-actions">{j.blob&&<button className="primary compact" onClick={()=>save(j)}>⇩ Download result ZIP</button>}</div></article>)}</div></section>}
 {tab==='guide'&&<section className="view enter"><div className="hero-copy"><p className="eyebrow">HOW IT WORKS</p><h1>One name. <span>Three honest outcomes.</span></h1><p>DebToIPA audits the full Debian payload locally before it decides what can run.</p></div><div className="guide-grid"><article><span>01</span><div><h3>Analyze</h3><p>Inspect every app, Mach-O helper, launch daemon, tweak loader, script, private framework, entitlement, and runtime path.</p></div></article><article><span>02</span><div><h3>Direct IPA</h3><p>A complete stock-compatible ARM64 app becomes a correctly structured unsigned IPA.</p></div></article><article><span>03</span><div><h3>Host IPA</h3><p>Blocked packages are rebuilt around DebToIPA's precompiled Swift host with translated resources and an in-app capability report.</p></div></article><article><span>04</span><div><h3>Port Project</h3><p>The editable Swift source, original payload, manifest, and replacement plan stay in the result for features that still need implementation.</p></div></article></div></section>}</div><nav className="bottom-nav"><button className={tab==='convert'?'active':''} onClick={()=>setTab('convert')}>✦<span>Convert</span></button><button className={tab==='jobs'?'active':''} onClick={()=>setTab('jobs')}>▤<span>Jobs</span>{jobs.some(j=>j.status==='working')&&<i/>}</button><button className={tab==='guide'?'active':''} onClick={()=>setTab('guide')}>▱<span>Guide</span></button></nav></main>
}
